# Generated by Django 5.0.6 on 2024-08-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_about_user_viable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='viable',
            new_name='visable',
        ),
    ]
